### PR TITLE
embed dancebox specs

### PR DESCRIPTION
**Pull request by girazoki**
Embed dancebox and alphanet relay specs into the binary

### CODE REVIEW

**Review by tmpolaczyk — APPROVED** [review]

**Comment by girazoki** [comment]
Bootnodes are still to be set, so we cannot merge this PR

**Comment by tmpolaczyk** [comment]
What is the command to try to sync a collator with this PR?

**Comment by girazoki** [comment]
It sbhould be `tanssi-node --chain=dancebox -- --chain=westend_moonbase_relay_testnet`

**Comment by girazoki** [comment]
but you need to provide bootnodes probably

**Review by tmpolaczyk — APPROVED** [review]
I was able to sync with the command above. There is a bug in warp sync, I had to restart the node after syncing the relay chain to be able to start the parachain warp sync. Before the restart, the warp sync was stuck with this log:

```
2024-02-21 14:30:58 [Orchestrator] ⏩ Warping, Downloading target block, 0.00 Mib (8 peers), best: #0 (0x27aa…43ea), finalized #0 (0x27aa…43ea), ⬇ 0.1kiB/s ⬆ 0.1kiB/s    
```

But after the restart I was able to warp sync in 30 seconds, excluding the block history step:

```
2024-02-21 14:31:29 [Orchestrator] Warp sync is complete (48 MiB), restarting block sync.    
```

**Pull request merged**
