### PR TITLE
Update moonwall to 5.9.1 and add --bail=1

### PR DESCRIPTION
**Pull request by tmpolaczyk**
The --bail=1 flag makes the tests stop on the first failure, as opposed to always executing all the tests. The zombie_data_preservers tests takes 40 minutes to fail because it waits for several tests to fail with timeout, with this it should fail in 10 minutes.

https://stackoverflow.com/a/78969381

**Requires node 22**

### CODE REVIEW

**Comment by ParthDesai** [comment]
@tmpolaczyk What does `--bail=1` do?

**Comment by tmpolaczyk** [comment]
> @tmpolaczyk What does `--bail=1` do?

Updated PR description

**Review by ParthDesai — APPROVED** [review]
Much needed. Thanks.

**Review by girazoki — APPROVED** [review]
thank you @tmpolaczyk

**Pull request merged**
