### PR TITLE
Add pallet relay storage roots

### PR DESCRIPTION
**Pull request by tmpolaczyk**
Adds a `pallet_relay_storage_roots`. This pallet stores the latest `MaxStorageRoots` relay storage roots, which can be used to verify state proofs against an old state of the relay chain.

See also https://github.com/moondance-labs/moonkit/pull/1/files and https://github.com/Moonsong-Labs/moonkit/pull/18

### CODE REVIEW

**Comment by tmpolaczyk** [comment]
Container chains won't compile because dancekit depends on moonkit, and I didn't make a new branch in dancekit. Will fix this after moonkit PR is merged I guess

**Comment by girazoki** [comment]
A few requested changes but otherwise looks good! I guess we should propose to dancekit or moonkit directly instead

**Comment by girazoki** [comment]
Looks good, but see the other PR as I made some comments there

**Review by girazoki — APPROVED** [review]

**Comment by girazoki** [comment]
LGTM!

**Pull request merged**
