### PR TITLE
Smoke test: check eligible candidates all have more than minimum self delegation

### PR DESCRIPTION
**Pull request by nanocryk**

### CODE REVIEW

**Review by girazoki — APPROVED** [review]
LGTM

**Comment by tmpolaczyk** [comment]
You need to run

```
pnpm fmt:fix
pnpm lint:fix
```

locally, and some of the lints need to be fixed manually.

**Comment by girazoki** [comment]
@nanocryk can you add a check to skip this test if we are below runtime 200?

**Review by tmpolaczyk — APPROVED** [review]

**Comment by tmpolaczyk** [comment]
Tests will pass if you merge master

**Pull request merged**
