### PR TITLE
XCM `DryRun` & `LocationToAccount` runtime APIs

### PR DESCRIPTION
**Pull request by fgamundi**
Adds `DryRun` and `LocationToAccount` XCM runtime APIs to Dancebox and the container chains runtimes

### CODE REVIEW

**Review by tmpolaczyk — APPROVED** [review]
Looks good. Is it worth it to add typescript tests?

**Comment by girazoki** [comment]
I think it is yes, the only thing is that you will need to create the runtime-api interface yourself @fgamundi

**Comment by tmpolaczyk** [comment]
Oh right... you have an example in `test/suites/common-xcm/xcm/test-xcm-payment-api.ts`

**Comment by fgamundi** [comment]
Added TS tests

**Review by ParthDesai — APPROVED** [review]
Looks good.

**Review by girazoki — APPROVED** [review]

**Pull request merged**
