### PR TITLE
Add binary download to moonwall

### PR DESCRIPTION
**Pull request by girazoki**
Removes docker polkadot download and injects it through moonwall scripts. This should help making the local testing process a bit smoother.

It does the same with the `pre-build-contracts` script and `build-spec` script

### CODE REVIEW

**Comment by tmpolaczyk** [comment]
Should we add `test/helpers/compiled/*.json` to `.gitignore`?

**Comment by girazoki** [comment]
we probably should yes

**Review by tmpolaczyk — APPROVED** [review]

**Comment by tmpolaczyk** [comment]
The tests are passing locally for me, no idea why are they failing in CI....

**Comment by girazoki** [comment]
its related to the increasing moonwall version, will have to look..

**Review by tmpolaczyk — APPROVED** [review]

**Pull request merged**
